import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import GlobalProvider from "./GlobalProvider";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-900 text-gray-50`}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
